# Generated by Django 4.1.7 on 2023-02-22 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Thing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("poster", models.URLField(blank=True)),
                ("illustration", models.URLField(blank=True)),
                ("image", models.URLField(blank=True)),
                ("caption", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Quest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField()),
                ("active", models.BooleanField()),
                ("description", models.TextField()),
                ("threewords", models.CharField(max_length=100)),
                ("map", models.URLField(blank=True)),
                ("things", models.ManyToManyField(to="quest.thing")),
            ],
        ),
    ]
