# Generated by Django 4.1.7 on 2023-03-09 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quest", "0003_thing_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="thing", name="teaser", field=models.TextField(blank=True),
        ),
    ]
